import VV.BBEKOneRootRecurrence

#print axioms VV.BBEKOneRootAtoms.scalar_atom_dichotomy
#print axioms VV.BBEKOneRootAtoms.exists_real_lower_atom_data
#print axioms VV.BBEKOneRootAtoms.exists_padic_lower_atom_data
#print axioms VV.BBEKOneRootAtoms.exists_real_upper_atom_data
#print axioms VV.BBEKOneRootAtoms.exists_padic_upper_atom_data
#print axioms VV.BBEKOneRootRecurrence.ae_translation_multiplier_eq_one_radius
#print axioms VV.BBEKOneRootRecurrence.scalar_projective_stabilizer_eq
#print axioms VV.BBEKOneRootRecurrence.exists_real_lower_exact_stabilizer_data
#print axioms VV.BBEKOneRootRecurrence.exists_padic_lower_exact_stabilizer_data
#print axioms VV.BBEKOneRootRecurrence.exists_real_upper_exact_stabilizer_data
#print axioms VV.BBEKOneRootRecurrence.exists_padic_upper_exact_stabilizer_data
